# Generated by Django 3.2 on 2021-05-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_rename_n0_of_questions_quiz_no_of_questions'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
