# Generated by Django 3.2 on 2021-05-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210506_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_l',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
