# Generated by Django 3.1.2 on 2021-05-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20210516_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image_l',
        ),
    ]
