# Generated by Django 3.1.2 on 2021-05-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_remove_question_image_l'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_l',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
