# Generated by Django 3.2 on 2021-05-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='n0_of_questions',
            new_name='no_of_questions',
        ),
    ]
