# Generated by Django 3.2 on 2021-05-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_auto_20210516_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image_logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
