# Generated by Django 3.2 on 2021-05-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_alter_quiz_image_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image_logo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
