# Generated by Django 3.1.2 on 2021-05-16 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0007_auto_20210516_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image_logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
