# Generated by Django 3.1.2 on 2021-05-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0008_quiz_image_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='image_logo',
        ),
    ]
