# Generated by Django 3.1.2 on 2021-05-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0009_remove_quiz_image_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image_logo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
