# Generated by Django 3.1.2 on 2021-05-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0010_quiz_image_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image_logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
